window.BOURSE_CONFIG={
  worker:"https://brsapi-proxy.yasharesmaeili.workers.dev",
  historyPath:"/tsetmc/history",
  searchPath:"/tsetmc/search",
  marketWatchPath:"/tsetmc/market-watch",
  quotePath:"/tsetmc/quote",
  orderbookPath:"/tsetmc/orderbook",
  clientTypePath:"/tsetmc/client-type",
  refreshIntervalMs:5000,
  staleAfterMs:15000,
  marketWatchFallbackUrl:"https://raw.githubusercontent.com/Esmal-Project/Bourse/main/data/market-watch.json"
};