window.BOURSE_CONFIG={
  worker:"https://brsapi-proxy.yasharesmaeili.workers.dev",
  historyPath:"/tsetmc/history",
  searchPath:"/tsetmc/search",
  marketWatchPath:"/tsetmc/market-watch",
  quotePath:"/tsetmc/quote",
  orderbookPath:"/tsetmc/orderbook",
  clientTypePath:"/tsetmc/client-type"
};