window.BOURSE_CONFIG={
  worker:"https://brsapi-proxy.yasharesmaeili.workers.dev",
  historyPath:"/tsetmc/history",
  searchPath:"/tsetmc/search",
  marketWatchPath:"/tsetmc/market-watch",
  quotePath:"/tsetmc/quote",
  orderbookPath:"/tsetmc/orderbook",
  clientTypePath:"/tsetmc/client-type",
  refreshIntervalMs:3000,
  marketWatchRefreshMs:5000,
  liveRefreshMs:1500,
  staleAfterMs:15000,
  snapshotCacheMs:60000,
  snapshotStaleAfterMs:720000,
  marketWatchFallbackUrl:"./data/market-watch.json",
  marketWatchFallbackUrlSecondary:"https://raw.githubusercontent.com/Esmal-Project/Bourse/main/data/market-watch.json"
};